# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a07b906e8acbb495d802593e116dd86963d3749185e04e0f7e3832e357ccdde40f51901e9841fecce85fe7bb29ff10bc6d6ee4199eb9f2f800a238a601583a2

test:
  secret_key_base: 6cca07f3d2cb68f0d84ed016cd1efb8be12784d763a713934ecbd7113d1bcb16b60ecc7e5b31245c9c89cb2ee0217db66d92fac34c92c726e3650a6e6b72b3ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
